add root certs for Genoa
google/go-sev-guest pull request #127
Opened 2024-07-08 10:57 UTC by Freax13

This PR adds the root ASK/ARK certs for Genoa. I'm not sure if AMD also distributes the certificates for Genoa in the older sevcert format we use for Milan, so I used the newer x509-based certificates instead.

2024-07-09 05:26 UTC, Freax13 commented
The CI failure seems to be unrelated to this PR and already happened in previous CI runs: https://github.com/google/go-sev-guest/actions/runs/8993363579/job/24705035892.

2024-07-09 13:39 UTC, deeglaze approved these changes

2024-07-09 17:02 UTC, deeglaze requested changes

2024-07-10 08:31 UTC, Freax13 commented
@deeglaze Now CI is failing because you haven't signed the CLA for the main E-Mail address linked to your GitHub account (i.e. the E-Mail address GitHub added a `Co-authored-by` tag for when I committed your suggestion).

2024-07-10 16:25 UTC, deeglaze approved these changes

2024-07-10 16:26 UTC, merged